import type { ContentBrief } from "./types";

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function slug(topic: string): string {
  return topic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const pct = (v: number) => `${Math.round(v * 100)}%`;

/** Render the brief as a clean, writer-ready Markdown document. */
export function briefToMarkdown(brief: ContentBrief): string {
  const { outline, score, keyword_clusters, usage } = brief;
  const lines: string[] = [];

  lines.push(`# ${outline.title}`, "");
  lines.push(`> ${outline.meta_description}`, "");
  lines.push(
    `**Topic:** ${brief.topic}  `,
    `**Target length:** ${outline.estimated_word_count.toLocaleString()} words  `,
    `**Competitors analyzed:** ${brief.competitor_pages_analyzed}`,
    "",
  );

  lines.push("## Quality Score", "");
  lines.push(`- **Overall:** ${pct(score.overall)}`);
  lines.push(`- **Keyword coverage:** ${pct(score.keyword_coverage)}`);
  lines.push(`- **Structure completeness:** ${pct(score.structure_completeness)}`);
  lines.push(`- **E-E-A-T signal:** ${pct(score.eeat_signal_score)}`);
  lines.push(`- **Readability grade:** ${score.readability_grade.toFixed(1)}`);
  if (score.notes.length) {
    lines.push("", "**Notes:**");
    score.notes.forEach((n) => lines.push(`- ${n}`));
  }
  lines.push("");

  lines.push("## Keyword Clusters", "");
  keyword_clusters.forEach((c) => {
    lines.push(`### ${c.primary_keyword} _(${c.intent})_`);
    if (c.related_keywords.length) {
      lines.push(c.related_keywords.map((k) => `\`${k}\``).join(", "));
    }
    lines.push("");
  });

  lines.push("## Suggested Outline", "");
  outline.sections.forEach((s) => {
    lines.push(`${"#".repeat(Math.min(s.level + 1, 6))} ${s.heading}`);
    s.talking_points.forEach((tp) => lines.push(`- ${tp}`));
    if (s.target_keywords.length) {
      lines.push(`_Target keywords: ${s.target_keywords.join(", ")}_`);
    }
    lines.push("");
  });

  if (outline.content_gaps_addressed.length) {
    lines.push("## Content Gaps Addressed", "");
    outline.content_gaps_addressed.forEach((g) => lines.push(`- ${g}`));
    lines.push("");
  }

  lines.push("---", "");
  lines.push(
    `_Generated by EMIAC SEO Intelligence · ${usage.total_tokens.toLocaleString()} tokens · ~$${usage.estimated_cost_usd.toFixed(4)}_`,
  );

  return lines.join("\n");
}

export function downloadMarkdown(brief: ContentBrief) {
  triggerDownload(
    `${slug(brief.topic)}-brief.md`,
    briefToMarkdown(brief),
    "text/markdown",
  );
}

export function downloadJson(brief: ContentBrief) {
  triggerDownload(
    `${slug(brief.topic)}-brief.json`,
    JSON.stringify(brief, null, 2),
    "application/json",
  );
}

/** PDF via the browser print dialog against a print-styled DOM node. */
export function downloadPdf() {
  window.print();
}
